version: "3"

vars:
  BINARY_NAME: gchess-server
  PKG: ./cmd/server/main.go

tasks:
  setup:
    desc: Setup the project
    cmds:
      - go mod tidy
      - go mod tidy -modfile=go.tool.mod

  upgrade:
    desc: Upgrade dependencies or tools (use `task upgrade -- tool`)
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" = "tool" ]; then
          go get -modfile=go.tool.mod tool
        else
          go tool -modfile=go.tool.mod go-mod-upgrade
        fi

  build:
    desc: Build the project
    cmds:
      - go build -o {{.BINARY_NAME}} {{.PKG}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./test/

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}

  lint:
    desc: Run linter
    cmds:
      - go tool -modfile=go.tool.mod golangci-lint run

  server:up:
    desc: Run the erver on docker container
    preconditions:
      - test -f ./compose.yml
    cmds:
      - docker compose -f ./compose.yml up --build

  server:down:
    desc: Shutdown the server docker container
    preconditions:
      - test -f ./compose.yml
    cmds:
      - docker compose -f ./compose.yml down

  server:local:
    desc: Run the game server locally
    cmds:
      - go mod download
      - go run ./cmd/server
